[files]
extend-exclude = [
    ".git",
    "public/build/assets/*",
    "resources/views/form/fields/editor.blade.php"
]
ignore-hidden = false
[default.extend-words]
responsable = "responsable"
# Disallow uninformative words
"i" = ""
"arr" = ""
"bool" = ""
"boolean" = ""
"cnt" = ""
"col" = ""
"coll" = ""
"custom" = ""
"detail" = ""
"data" = ""
"double" = ""
"elem" = ""
"err" = ""
"extra" = ""
"float" = ""
"impl" = ""
"ind" = ""
"info" = ""
"int" = ""
"integer" = ""
"item" = ""
"iter" = ""
"key" = ""
"len" = ""
"more" = ""
"other" = ""
"proc" = ""
"req" = ""
"res" = ""
"ret" = ""
"return" = ""
"str" = ""
"value" = ""
"var" = ""
"vdata" = ""
