name: Back-end

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  unit_tests:

    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-20.04", "windows-latest"]
        php: ["8.0", "8.1"]
        stability: ["prefer-stable"]
        laravel: ["8.0", "9.0"]

    name: "Unit - ${{ matrix.os }} - PHP ${{ matrix.php }} - ${{ matrix.stability }}"

    runs-on: "${{ matrix.os }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, fileinfo, exif
          tools: composer:v2
          coverage: pcov

      - name: Check Composer configuration
        run: composer validate --strict

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Upgrade to Laravel 9
        if: matrix.laravel == '9.0'
        run: composer require --no-interaction --no-progress --${{ matrix.stability }} --prefer-dist --with-all-dependencies 'laravel/framework:dev-master as 9.0.0' laravel/laravel:dev-master inertiajs/inertia-laravel:dev-laravel-9 'symfony/console:^6.0'

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
