name: "Vue.JS"

on:
  push:
    branches: [ "master" ]
  pull_request: null

jobs:
  tests:
    name: "Tests"
    strategy:
      matrix:
        node-version:
          - "16"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Set up NodeJS"
        uses: "actions/setup-node@v2"
        with:
          node-version: "${{ matrix.node-version }}"

      - name: "Configure yarn"
        run: "yarn config set engine-strict true"

      - name: "Install dependencies"
        run: "yarn install --non-interactive --pure-lockfile"

      - name: "Run linter"
        run: "yarn run lint --format json --output-file /tmp/eslint_report.json"
        continue-on-error: true

      - name: "Annotate Code Linting Results"
        uses: "ataylorme/eslint-annotate-action@1.1.2"
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "/tmp/eslint_report.json"

      - name: "Run tests"
        run: "yarn run test --color"

      - name: "Run SASS linter"
        run: "yarn run lint-sass"

  build:
    name: "Build"
    strategy:
      matrix:
        node-version:
          - "16"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Set up NodeJS"
        uses: "actions/setup-node@v2"
        with:
          node-version: "${{ matrix.node-version }}"

      - name: "Configure yarn"
        run: "yarn config set engine-strict true"

      - name: "Install dependencies"
        run: "yarn install --non-interactive --pure-lockfile --production"

      - name: "Build front-end"
        run: "yarn run production"
